CREATE TABLE IF NOT EXISTS phones (phoneID SERIAL PRIMARY KEY, phone VARCHAR(64) NOT NULL);
CREATE TABLE IF NOT EXISTS emails (emailID SERIAL PRIMARY KEY, email VARCHAR(64) NOT NULL);

INSERT INTO phones (phoneID, phone) VALUES
(DEFAULT, '+7 911 154 67 77'),
(DEFAULT, '89111547676');

INSERT INTO emails (emailID, email) VALUES
(DEFAULT, 'ajamking@google.com'),
(DEFAULT, 'tedtoev@mail.ru');
