CREATE TABLE IF NOT EXISTS Phones (PhoneID SERIAL PRIMARY KEY, Phone VARCHAR(64) NOT NULL);
CREATE TABLE IF NOT EXISTS Emails (EmailID SERIAL PRIMARY KEY, Email VARCHAR(64) NOT NULL);

INSERT INTO Phones (PhoneID, Phone) VALUES
(DEFAULT, '+7 911 154 67 77'),
(DEFAULT, '89111547676');

INSERT INTO Emails (EmailID, Email) VALUES
(DEFAULT, 'ajamking@google.com'),
(DEFAULT, 'tedtoev@mail.ru');